### ISSUE TITLE
README:  add a screenshot

### ISSUE THREAD

**Issue by mciverza** [lsdopen/ahoy#10]
Please add a screenshot to README
so at a glance, visitors can see what the interface looks like
to see if they want to explore it further.

**Comment by clivebor** [comment]
Thanks for the log @mciverza 

We are busy with the design; so we'll add the screenshot once the design has been finalized.

**Comment by clivebor** [comment]
@mciverza maybe check out the screenshots and intro in the README and let me know what you think 👍
